name: Build and Release mtr (x86_64 Static)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autotools-dev automake libncurses5-dev make gcc
          sudo apt-get install -y gh

      - name: Bootstrap
        run: ./bootstrap.sh

      - name: Configure (Static Build)
        run: |
          ./configure CFLAGS="-static" LDFLAGS="-static" --prefix=/usr/local

      - name: Build
        run: make -j$(nproc)

      - name: Package binaries
        run: |
          mkdir -p release
          cp mtr mtr-packet release/
          strip release/mtr release/mtr-packet

          # 将两个文件打包为 .tar.gz
          tar -czvf release/mtr-static-x86_64.tar.gz -C release/ mtr mtr-packet

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: mtr-static-x86_64
          path: release/mtr-static-x86_64.tar.gz

      - name: List release directory files
        run: ls -l release

      - name: Check if tar file exists
        run: |
          if [ -f release/mtr-static-x86_64.tar.gz ]; then
            echo "Tar file exists."
          else
            echo "Tar file does not exist."
            exit 1
          fi

      - name: Get latest tag
        id: git_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release using gh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.git_tag.outputs.tag }} release/mtr-static-x86_64.tar.gz -t "mtr Static Build (${{ steps.git_tag.outputs.tag }})" -n "**静态编译的 mtr 工具包（包含 `mtr` 和 `mtr-packet`）**
          - 架构: x86_64
          - 编译时间: ${{ github.run_created_at }}
          - Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
