name: Build mtr for x86_64 (Static)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autotools-dev automake libncurses5-dev make gcc

      - name: Bootstrap
        run: ./bootstrap.sh

      - name: Configure (Static Build)
        run: |
          ./configure CFLAGS="-static" LDFLAGS="-static" --prefix=/usr/local

      - name: Build
        run: make -j$(nproc)

      - name: Package binaries
        run: |
          mkdir -p release
          cp mtr release/mtr                # 主程序
          cp mtr-packet release/mtr-packet  # 必须包含此文件
          strip release/mtr release/mtr-packet

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mtr-static-x86_64
          path: release/
